
default: &default
  adapter: postgresql
  encoding: unicode
  username: oleg
  password: oleg
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: item_collection_development

test:
  <<: *default
  database: item_collection_test

production:
  <<: *default
  database: item_collection_production
